### ISSUE TITLE
Point Blank Sniper error

### ISSUE THREAD

**Issue by kbachnik** [TheMouseNest/PointBlankSniper#10]
I just reinstalled Auctionator and Auctioneer and these errors appeared when starting the scan

(FIRST ERROR)

16x ...rce_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:245: attempt to index field '?' (a nil value)
[string "@Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua"]:245: in function `CancelNextAuction'
[string "*Main.xml:70_OnClick"]:1: in function <[string "*Main.xml:70_OnClick"]:1>

Locals:
self = Frame {
 0 = <userdata>
 NextStep = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:82
 SearchForUndercuts = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:160
 currentAuction = <table> {
 }
 CancelNextAuction = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:237
 CancelNextButton = AuctionatorCancelUndercutButton {
 }
 undercutAuctions = <table> {
 }
 SetCancel = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:57
 ReceiveEvent = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:139
 OnShow = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:30
 OnLoad = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:17
 StartScanButton = Button {
 }
 ProcessUndercutResult = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:220
 OnEvent = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:118
 StartScan = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:39
 seenAuctionResults = <table> {
 }
 scanIndex = 133
 expectedItemKey = <table> {
 }
 ProcessSearchResults = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:183
 OnHide = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:34
 EndScan = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:61
}
(*temporary) = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:56
(*temporary) = <table> {
 RegisterSource = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:44
 Unregister = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:28
 Register = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:9
 queue = <table> {
 }
 IsSourceRegistered = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:40
 sources = <table> {
 }
 Init = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:3
 Fire = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:56
 UnregisterSource = <function> defined @Auctionator/Source/Utilities/EventBusMixin.lua:50
 registeredListeners = <table> {
 }
}
(*temporary) = Frame {
 0 = <userdata>
 NextStep = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:82
 SearchForUndercuts = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:160
 currentAuction = <table> {
 }
 CancelNextAuction = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:237
 CancelNextButton = AuctionatorCancelUndercutButton {
 }
 undercutAuctions = <table> {
 }
 SetCancel = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:57
 ReceiveEvent = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:139
 OnShow = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:30
 OnLoad = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:17
 StartScanButton = Button {
 }
 ProcessUndercutResult = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutScan.lua:220
 OnEvent = <function> defined @Auctionator/Source_Mainline/Tabs/Cancelling/Mixins/UndercutSca

**Comment by kbachnik** [comment]
(SECOND ERROR)

1x ...cePointBlankSniper/Source/Scan/NameCache.lua:112: attempt to index field '?' (a nil value)
[string "@PointBlankSniper/Source/Scan/NameCache.lua"]:112: in function `CacheAndProcessSearchResults'
[string "@PointBlankSniper/Source/Scan/NameCache.lua"]:217: in function <...cePointBlankSniper/Source/Scan/NameCache.lua:212>

Locals:
self = Frame {
 0 = <userdata>
 thresholdCheck = <function> defined @PointBlankSniper/Source/Tab/Main.lua:179
 priceCheck = <table> {
 }
 ProcessCachedResults = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:165
 blankSearchResultsWaiting = 0
 SetThresholdCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:24
 GotAnyTerms = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:28
 SetPriceCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:12
 searchFor = <table> {
 }
 OnLoad = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:3
 OnHide = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:8
 SetCategories = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:16
 CacheAndProcessSearchResults = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:74
 OnEvent = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:212
 SetList = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:20
 DoShoppingListSearch = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:118
 Stop = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:199
 registered = true
 Start = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:37
 cancelled = false
 CachingCompleteCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:68
 results = <table> {
 }
}
addedResults = <table> {
}
resultsInfo = <table> {
 cache = <table> {
 }
 cachingComplete = false
 announcedReady = true
 namesWaiting = 0
 names = <table> {
 }
}
CleanSearchString = <function> defined @PointBlankSniper/Source/Utilities/Main.lua:3
(*temporary) = <function> defined @PointBlankSniper/Source/Tab/Main.lua:179
(*temporary) = nil
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by plusmouse** [comment]
What did you do to trigger these errors? As the first looks like an undercut scan in the Cancelling tab, not Point Blank Sniper.

**Comment by kbachnik** [comment]
Only this value changes all the time. But not the Processing batch
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/00c06822-5fc5-4b7a-895e-d24fdbafa3d6)

**Comment by kbachnik** [comment]
Just reinstall  Auctionator and Auctioneer
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/72df202b-2782-4771-a8e3-0199233c2e09)

**Comment by kbachnik** [comment]
undercut scan works well

**Comment by plusmouse** [comment]
Are you on the newest version of Point Blank Sniper too?

**Comment by kbachnik** [comment]
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/8b5383aa-c8c4-410d-a804-05f4b4fa35ee)
 Yes

**Comment by kbachnik** [comment]
Let me try reinstall PBS

**Comment by plusmouse** [comment]
Can you try using the latest alpha for pbs?

**Comment by plusmouse** [comment]
- it looks like I did a code update on April 1st, but never changed it to a release build, and left it on alpha (fixed now, just processing by Curseforge/Wago now)

**Comment by kbachnik** [comment]
Yes, 1 min

**Comment by kbachnik** [comment]
1x ...cePointBlankSniper/Source/Scan/NameCache.lua:113: attempt to index field '?' (a nil value)
[string "@PointBlankSniper/Source/Scan/NameCache.lua"]:113: in function `CacheAndProcessSearchResults'
[string "@PointBlankSniper/Source/Scan/NameCache.lua"]:247: in function <...cePointBlankSniper/Source/Scan/NameCache.lua:242>

Locals:
self = Frame {
 0 = <userdata>
 thresholdCheck = <function> defined @PointBlankSniper/Source/Tab/Main.lua:179
 priceCheck = <table> {
 }
 ProcessCachedResults = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:179
 blankSearchResultsWaiting = 0
 SetThresholdCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:24
 GotAnyTerms = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:28
 SetPriceCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:12
 searchFor = <table> {
 }
 OnLoad = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:3
 OnHide = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:8
 SetCategories = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:16
 CacheAndProcessSearchResults = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:74
 OnEvent = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:242
 SetList = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:20
 DoShoppingListSearch = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:132
 Stop = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:229
 registered = true
 Start = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:37
 cancelled = false
 CachingCompleteCheck = <function> defined @PointBlankSniper/Source/Scan/NameCache.lua:68
 results = <table> {
 }
}
addedResults = <table> {
}
resultsInfo = <table> {
 cachingComplete = false
 cache = <table> {
 }
 missing = false
 announcedReady = true
 namesWaiting = 0
 names = <table> {
 }
}
CleanSearchString = <function> defined @PointBlankSniper/Source/Utilities/Main.lua:3
(*temporary) = <function> defined @PointBlankSniper/Source/Tab/Main.lua:179
(*temporary) = nil
(*temporary) = 0
(*temporary) = false
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by kbachnik** [comment]
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/2d321290-0661-4793-b588-6007ba58e226)

**Comment by plusmouse** [comment]
Try running the scan with just Auctionator and PBS enabled.

**Comment by kbachnik** [comment]
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/e6680cb0-5d02-49c8-ab9f-e4847be61978)

Only Round value changes all the time, not the Processing batch

And there is no new bugs in BugSack

**Comment by plusmouse** [comment]
That's because you are now using the wrong scan mode for what you're trying to search for. You probably want Blank

**Comment by kbachnik** [comment]
Oh yes, I forgot to switch it when I was testing. Thank you! Everything works fine, problem solved.
