### ISSUE TITLE
Auctionator Shopping scan

### ISSUE THREAD

**Issue by kbachnik** [TheMouseNest/PointBlankSniper#11]
It doesn't work correctly. It shows things that are not on the list. You can see the results list is bigger than the scan list

![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/62a01678-c7d4-4715-b7b5-850e3e4c8046)

![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/6713440b-d311-49eb-8f03-f1ec546ab904)

**Comment by plusmouse** [comment]
There will be an item in your shopping list that includes a lot of results.
