### ISSUE TITLE
PBS Buttons 

### ISSUE THREAD

**Issue by kbachnik** [TheMouseNest/PointBlankSniper#12]
Hi, after that bug ive reported, you advice me to change PBS on Alpha version. Than buttons in PBS changed to
![image](https://github.com/Auctionator/PointBlankSniper/assets/36343167/8b868934-91de-40d5-bc2b-93c74af659c1)

How can i change it to previous version? Like, there was only 2 buttons, buy and show listing. 
Name search not comfortable because takes to much time to went to shopping list and scan items. It was better on the previous version when the auction page opened immediately. 

I already reinstall PBS and change Release type on "Release", not helps

**Comment by plusmouse** [comment]
The "Blizzard Buy UI" button will do what the previous "View All" button did

**Comment by kbachnik** [comment]
Noted, thx
