### ISSUE TITLE
Buy-macro on first use

### ISSUE THREAD

**Issue by chrischtili** [TheMouseNest/PointBlankSniper#5]
The first use of the buy macro (nothing has been found yet), but provisionally I like to start the macro right after opening PBS, leads to the following error:

Message: [string "PointBlankSniperTabFrame.Buy.BuyButton:Clic..."]:1: attempt to index global 'PointBlankSniperTabFrame' (a nil value)
Time: Thu Dec 22 06:26:58 2022
Count: 55
Stack: [string "PointBlankSniperTabFrame.Buy.BuyButton:Clic..."]:1: attempt to index global 'PointBlankSniperTabFrame' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "PointBlankSniperTabFrame.Buy.BuyButton:Click()"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@Interface/FrameXML/ChatFrame.lua"]:2170: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:3132: in function <Interface/FrameXML/ChatFrame.lua:3125>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON4"]:2: in function <[string "ACTIONBUTTON4"]:1>

Locals: (*temporary) = "down"
(*temporary) = <function> defined =[C]:-1

**Comment by plusmouse** [comment]
The error is from activating the macro before PBS has finished loading. This doesn't need fixing, just don't use the macro until the PBS tab is open.

**Comment by chrischtili** [comment]
I am in the PBS tab: Now I definitely have to wait until the first auction pops up. Only then the macro works. Otherwise the error message
