### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by bozoweed** [TheMouseNest/PointBlankSniper#6]
hi , 
fisrt of all, thank you for this amazing work, 

but is it possible to associate "carry on after finding" with auto buyout ?

or something like that ? 

i mean i setted up my items list with max price , then when it's found , it's auto open offer but i need to manually click on buyout , 

is it possible to automate this ? without lua unlocker

**Comment by plusmouse** [comment]
You'll have to click or press a button to do the buyout, that's just how Blizzard have set stuff up. You can macro the buy button though
```
 /run PointBlankSniperTabFrame.Buy.BuyButton:Click() 
```

**Comment by bozoweed** [comment]
okey thank u :)
