### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Fabio254** [TheMouseNest/PointBlankSniper#7]
Would it be possible that you add an option in the basic options to not show Bid Only items? They seem rather annoying when im trying to snipe other stuff because you cant get rid of them.

![bidonly](https://user-images.githubusercontent.com/92888689/209567340-199d839e-ee1d-48a9-8803-039fe3745a37.PNG)

**Comment by plusmouse** [comment]
It isn't possible to filter out bid-only items in the initial search as the Blizzard API doesn't contain any information indicating that it is bid only.
