### ISSUE TITLE
Bug: shift + left click on item to search doesn't work anymore.

### ISSUE THREAD

**Issue by zeenk** [TheMouseNest/PointBlankSniper#9]
Noticed that shift + left clicking on the item name to put it in the search bar doesn't work anymore from view all tab, honestly could probably just remove the view all button now that we have search all that does the same thing + more, but maybe I'm missing something that view all still has some use for? (just an idea if you don't want to fix this bug)

![2023-03-31_01-32-15](https://user-images.githubusercontent.com/68170439/228987335-7acda1fd-3278-41d1-ad4e-b74cda77c11c.png)

**Comment by plusmouse** [comment]
This particular bug isn't fixable - as the solution will cause a protected action error in some circumstances, which sometimes results in breaking health potions during a fight

**Comment by plusmouse** [comment]
Any thoughts on this redesign?
![image](https://user-images.githubusercontent.com/60280559/229190576-cc8322a0-4f08-4ef3-aa4e-096d6f63091e.png)

**Comment by plusmouse** [comment]
Second thoughts, going to leave the buttons as they are - for now it will just be a legacy button from before the "Buy Now" button existed.
